spring.application.name=release
# connexion postgres
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/bovin_db
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Emplacement des fichiers HTML (par défaut : classpath:/templates/)
spring.thymeleaf.prefix=classpath:/templates/

# Extension des fichiers de template (par défaut : .html)
spring.thymeleaf.suffix=.html

# Encodage des fichiers (par défaut : UTF-8)
spring.thymeleaf.encoding=UTF-8

# Type de contenu pour le rendu (par défaut : text/html)
spring.thymeleaf.servlet.content-type=text/html

# Mode de validation du code HTML (HTML, XML, TEXT, etc.)
spring.thymeleaf.mode=HTML

# Désactivation du cache pour voir les modifications en temps réel sans redémarrer
spring.thymeleaf.cache=false

# Activation du support Thymeleaf (activé par défaut)
spring.thymeleaf.enabled=true
